name: CI

on:
  pull_request:
    branches: ["main", "dev-database"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      CI_COMMIT_BRANCH: ${{ github.ref_name }}
      CI_PULL_REQUEST_BASE: ${{ github.base_ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache libs
        uses: actions/cache@v3
        with:
          path: libs
          key: libs-cache-${{ hashFiles('libs/*.jar') }}

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Build
        run: bash scripts/build.sh

      # TODO: переписать unit-тесты под новую архитектуру.
      #- name: Run unit tests
      #  run: bash scripts/unit-test.sh

      - name: Run app tests
        run: bash scripts/app-test.sh

      # TODO: реализация тестов через SonarCloud
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          CI_COMMIT_REF_NAME: ${{ env.CI_COMMIT_REF_NAME }}
          CI_COMMIT_BRANCH: ${{ env.CI_COMMIT_BRANCH }}
          CI_PULL_REQUEST_BASE: ${{ env.CI_PULL_REQUEST_BASE}}

      - name: Notify Telegram (success)
        if: success()
        run: |
          curl -s \
            -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="CI УСПЕХ PR #${{ github.event.pull_request.number }} (%0Arepo: ${{ github.repository }}%0Acommit: ${{ github.sha }})"

      - name: Notify Telegram (failure)
        if: failure()
        run: |
          curl -s \
            -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="CI ОШИБКА PR #${{ github.event.pull_request.number }} (%0Arepo: ${{ github.repository }}%0Acommit: ${{ github.sha }})"